/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ER1301.joinMe.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JFrame;

/**
 *
 * @author Andrea
 */
public class registrarUsuario extends javax.swing.JFrame {
    /**
     * Creates new form registrarUsuario
     */
    public registrarUsuario() {
        initComponents();
        loginUsuario.setForeground(java.awt.Color.GRAY);
        emailUsuario.setForeground(java.awt.Color.GRAY);
        contraUsuario.setForeground(java.awt.Color.GRAY);
        realUsuario.setForeground(java.awt.Color.GRAY);
        apellidosUsuario.setForeground(java.awt.Color.GRAY);
        
        loginUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (loginUsuario.getText().equals("Nombre de usuario")) {
                    loginUsuario.setText("");
                    loginUsuario.setForeground(java.awt.Color.BLACK);
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (loginUsuario.getText().equals("")) {
                    loginUsuario.setText("Nombre de usuario");
                    loginUsuario.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        emailUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (emailUsuario.getText().equals("Email")) {
                    emailUsuario.setText("");
                    emailUsuario.setForeground(java.awt.Color.BLACK);
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (emailUsuario.getText().equals("")) {
                    emailUsuario.setText("Email");
                    emailUsuario.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        contraUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (contraUsuario.getText().equals("Contraseña (mínimo 6 caracteres)")) {
                    contraUsuario.setText("");
                    contraUsuario.setForeground(java.awt.Color.BLACK);
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (contraUsuario.getText().equals("")) {
                    contraUsuario.setText("Contraseña (mínimo 6 caracteres)");
                    contraUsuario.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        realUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (realUsuario.getText().equals("Nombre real")) {
                    realUsuario.setText("");
                    realUsuario.setForeground(java.awt.Color.BLACK);
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (realUsuario.getText().equals("")) {
                    realUsuario.setText("Nombre real");
                    realUsuario.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        apellidosUsuario.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                if (apellidosUsuario.getText().equals("Apellidos")) {
                    apellidosUsuario.setText("");
                    apellidosUsuario.setForeground(java.awt.Color.BLACK);
                }

            }

            @Override
            public void focusLost(FocusEvent e) {
                if (apellidosUsuario.getText().equals("")) {
                    apellidosUsuario.setText("Apellidos");
                    apellidosUsuario.setForeground(java.awt.Color.GRAY);
                }
            }
        });
        
        ActionListener volverFunc = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                    loginForm.main(null);
                    dispose();
            }
        }; 
        volverButton.addActionListener(volverFunc);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginUsernameTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        loginUsernameTextField5 = new javax.swing.JTextField();
        loginUsernameTextField9 = new javax.swing.JTextField();
        loginUsernameTextField10 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        loginUsernameTextField11 = new javax.swing.JTextField();
        loginUsernameTextField12 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        loginUsernameTextField13 = new javax.swing.JTextField();
        loginUsernameTextField14 = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        loginUsernameTextField = new javax.swing.JTextField();
        loginUsernameTextField1 = new javax.swing.JTextField();
        loginUsernameTextField3 = new javax.swing.JTextField();
        loginUsernameTextField4 = new javax.swing.JTextField();
        loginUsernameTextField6 = new javax.swing.JTextField();
        loginUsernameTextField7 = new javax.swing.JTextField();
        loginUsernameTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        loginButton = new javax.swing.JButton();
        VolverButton = new javax.swing.JTextField();
        loginUsernameTextField20 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        loginUsuario = new javax.swing.JTextField();
        emailUsuario = new javax.swing.JTextField();
        contraUsuario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        realUsuario = new javax.swing.JTextField();
        apellidosUsuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        registerButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();

        loginUsernameTextField2.setText("Nombre de usuario");
        loginUsernameTextField2.setToolTipText("");
        loginUsernameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Datos de usuario");

        loginUsernameTextField5.setText("Nombre de usuario");
        loginUsernameTextField5.setToolTipText("");
        loginUsernameTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField5ActionPerformed(evt);
            }
        });

        loginUsernameTextField9.setText("Email ");
        loginUsernameTextField9.setToolTipText("");
        loginUsernameTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField9ActionPerformed(evt);
            }
        });

        loginUsernameTextField10.setText("Contraseña (mínimo 6 caracteres) ");
        loginUsernameTextField10.setToolTipText("");
        loginUsernameTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField10ActionPerformed(evt);
            }
        });

        jLabel6.setText("Datos personales");

        loginUsernameTextField11.setText("Nombre real");
        loginUsernameTextField11.setToolTipText("");
        loginUsernameTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField11ActionPerformed(evt);
            }
        });

        loginUsernameTextField12.setText("Apellidos");
        loginUsernameTextField12.setToolTipText("");
        loginUsernameTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField12ActionPerformed(evt);
            }
        });

        jLabel7.setText("Edad");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18", "19", "20", "21" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jLabel8.setText("Género");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer", "Otro" }));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        loginUsernameTextField13.setText("Registrarse");
        loginUsernameTextField13.setToolTipText("");
        loginUsernameTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField13ActionPerformed(evt);
            }
        });

        loginUsernameTextField14.setText("Volver");
        loginUsernameTextField14.setToolTipText("");
        loginUsernameTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField14ActionPerformed(evt);
            }
        });

        jInternalFrame1.setVisible(true);

        loginUsernameTextField.setText("Contraseña (mínimo 6 caracteres) ");
        loginUsernameTextField.setToolTipText("");
        loginUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextFieldActionPerformed(evt);
            }
        });

        loginUsernameTextField1.setText("Nombre real");
        loginUsernameTextField1.setToolTipText("");
        loginUsernameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField1ActionPerformed(evt);
            }
        });

        loginUsernameTextField3.setText("Email ");
        loginUsernameTextField3.setToolTipText("");
        loginUsernameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField3ActionPerformed(evt);
            }
        });

        loginUsernameTextField4.setText("Nombre de usuario");
        loginUsernameTextField4.setToolTipText("");
        loginUsernameTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField4ActionPerformed(evt);
            }
        });

        loginUsernameTextField6.setText("Apellidos");
        loginUsernameTextField6.setToolTipText("");
        loginUsernameTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField6ActionPerformed(evt);
            }
        });

        loginUsernameTextField7.setText("Volver");
        loginUsernameTextField7.setToolTipText("");
        loginUsernameTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField7ActionPerformed(evt);
            }
        });

        loginUsernameTextField8.setText("Registrarse");
        loginUsernameTextField8.setToolTipText("");
        loginUsernameTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos de usuario");

        jLabel2.setText("Edad");

        jLabel3.setText("Género");

        jLabel4.setText("Datos personales");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer", "Otro" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18", "19", "20", "21" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loginUsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginUsernameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginUsernameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginUsernameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(loginUsernameTextField7))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(loginUsernameTextField8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(54, 54, 54))))))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(loginUsernameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsernameTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsernameTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginUsernameTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        loginButton.setText("Iniciar sesión");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        VolverButton.setText("Volver");
        VolverButton.setToolTipText("");
        VolverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverButtonActionPerformed(evt);
            }
        });

        loginUsernameTextField20.setText("Registrarse");
        loginUsernameTextField20.setToolTipText("");
        loginUsernameTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsernameTextField20ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel9.setText("Datos de usuario");

        loginUsuario.setText("Nombre de usuario");
        loginUsuario.setToolTipText("");
        loginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginUsuarioActionPerformed(evt);
            }
        });

        emailUsuario.setText("Email");
        emailUsuario.setToolTipText("");
        emailUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailUsuarioActionPerformed(evt);
            }
        });

        contraUsuario.setText("Contraseña (mínimo 6 caracteres)");
        contraUsuario.setToolTipText("");
        contraUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraUsuarioActionPerformed(evt);
            }
        });

        jLabel10.setText("Datos personales");

        realUsuario.setText("Nombre real");
        realUsuario.setToolTipText("");
        realUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realUsuarioActionPerformed(evt);
            }
        });

        apellidosUsuario.setText("Apellidos");
        apellidosUsuario.setToolTipText("");
        apellidosUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apellidosUsuarioActionPerformed(evt);
            }
        });

        jLabel11.setText("Edad");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18", "19", "20", "21" }));
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });

        jLabel12.setText("Género");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hombre", "Mujer", "Otro" }));
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });

        registerButton.setText("Registrarse");
        registerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerButtonMouseClicked(evt);
            }
        });
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(realUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(contraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(apellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(volverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(50, 50, 50))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(realUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(volverButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginUsernameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void loginUsernameTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField8ActionPerformed

    private void loginUsernameTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField7ActionPerformed

    private void loginUsernameTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField6ActionPerformed

    private void loginUsernameTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField4ActionPerformed

    private void loginUsernameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField3ActionPerformed

    private void loginUsernameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField1ActionPerformed

    private void loginUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextFieldActionPerformed

    private void loginUsernameTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField5ActionPerformed

    private void loginUsernameTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField9ActionPerformed

    private void loginUsernameTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField10ActionPerformed

    private void loginUsernameTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField11ActionPerformed

    private void loginUsernameTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField12ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void loginUsernameTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField13ActionPerformed

    private void loginUsernameTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField14ActionPerformed

    private void loginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsuarioActionPerformed

    private void emailUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailUsuarioActionPerformed

    private void contraUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraUsuarioActionPerformed

    private void realUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_realUsuarioActionPerformed

    private void apellidosUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apellidosUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apellidosUsuarioActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void loginUsernameTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginUsernameTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginUsernameTextField20ActionPerformed

    private void VolverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VolverButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        
    }//GEN-LAST:event_registerButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverButtonActionPerformed

    private void registerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerButtonMouseClicked
        // TODO:
        //  - Verify user data befor singup
        
        if(Main.model
            .addUser(loginUsuario.getText(), contraUsuario.getText(), null, realUsuario.getText(), apellidosUsuario.getText())
            .login(loginUsuario.getText(), contraUsuario.getText())){
                //User's successfuly signedup and logged in, navigate to main view
                mainForm.main(null);
                dispose();
        }else{
            //Error during singup and login
            //TODO:
            //  - show error
        }
    }//GEN-LAST:event_registerButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new registrarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField VolverButton;
    private javax.swing.JTextField apellidosUsuario;
    private javax.swing.JTextField contraUsuario;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginUsernameTextField;
    private javax.swing.JTextField loginUsernameTextField1;
    private javax.swing.JTextField loginUsernameTextField10;
    private javax.swing.JTextField loginUsernameTextField11;
    private javax.swing.JTextField loginUsernameTextField12;
    private javax.swing.JTextField loginUsernameTextField13;
    private javax.swing.JTextField loginUsernameTextField14;
    private javax.swing.JTextField loginUsernameTextField2;
    private javax.swing.JTextField loginUsernameTextField20;
    private javax.swing.JTextField loginUsernameTextField3;
    private javax.swing.JTextField loginUsernameTextField4;
    private javax.swing.JTextField loginUsernameTextField5;
    private javax.swing.JTextField loginUsernameTextField6;
    private javax.swing.JTextField loginUsernameTextField7;
    private javax.swing.JTextField loginUsernameTextField8;
    private javax.swing.JTextField loginUsernameTextField9;
    private javax.swing.JTextField loginUsuario;
    private javax.swing.JTextField realUsuario;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
