/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ER1301.joinMe.view;

import ER1301.joinMe.model.GrupoDifusion;
import ER1301.joinMe.model.Mensaje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author Andrea
 */
public class verGrupoDifusion extends javax.swing.JFrame {

    private void reloadUserList() {

        String[] usuarios = Main.tempGroup.getListaUsuariosGrupo().toArray(new String[Main.tempGroup.getListaUsuariosGrupo().size()]);

        usersList.setModel(new javax.swing.AbstractListModel() {
            public int getSize() {
                return usuarios.length;
            }

            public Object getElementAt(int i) {
                return usuarios[i];
            }
        });
        setLocationRelativeTo(null);
    }

    private void reloadAllUserList() {

        String[] usuarios = Main.model.getUsersNames().toArray(new String[Main.model.getUsersNames().size()]);

        allUsersList.setModel(new javax.swing.DefaultComboBoxModel() {
            public int getSize() {
                return usuarios.length;
            }

            public Object getElementAt(int i) {
                return usuarios[i];
            }
        });

        setLocationRelativeTo(null);
    }

    /**
     * Creates new form gruposDifusionDetalles
     */
    public verGrupoDifusion() {
        initComponents();
        setLocationRelativeTo(null);

        mensaje.setForeground(java.awt.Color.GRAY);
        comentario.setForeground(java.awt.Color.GRAY);

        ActionListener addUserLogedToGroup = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.tempGroup.addUsuarioGrupoDifusion(Main.logedInUser.getName());
                reloadUserList();
            }
        };
        addMeGroup.addActionListener(addUserLogedToGroup);

        ActionListener addUserToGroup = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                allUsersList.getSelectedItem();

                if ((allUsersList.getSelectedItem() != null) && Main.model.getUsersNames().contains(allUsersList.getSelectedItem())) {
                    Main.tempGroup.addUsuarioGrupoDifusion(allUsersList.getSelectedItem().toString());
                }
                reloadUserList();
            }
        };
        addUser.addActionListener(addUserToGroup);

        ActionListener sendMessageUsers = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                Mensaje msg = new Mensaje(
                        "Mensaje de grupo" + Main.tempGroup.getIdGrupoDifusion(),
                        mensaje.getText(), Main.tempGroup.getIdGrupoDifusion(),
                        Main.tempGroup.getIdGrupoDifusion());

                Main.tempGroup.addMsg(msg);
                reloadUserList();
            }
        };
        sendMessage.addActionListener(sendMessageUsers);

        ActionListener volver = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                grupoDifusionForm.main(null);
                dispose();
            }
        };
        volverButton.addActionListener(volver);

        if (!(Main.tempGroup.getListaUsuariosGrupo().isEmpty())) {
            reloadUserList();
        }

        reloadAllUserList();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersList = new javax.swing.JList();
        volverButton = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        mensaje = new javax.swing.JTextField();
        comentario = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        addMeGroup = new javax.swing.JButton();
        allUsersList = new javax.swing.JComboBox();
        sendMessage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Lista de Usuarios del Grupo");

        usersList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(usersList);

        volverButton.setText("Volver");

        addUser.setText("Agregar usuario");

        mensaje.setText("Escribir mensaje");

        comentario.setText("Escribir comentario");

        jButton5.setText("Publicar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        addMeGroup.setText("Unirse a grupo");

        allUsersList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        sendMessage.setText("Enviar mensaje");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(allUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addUser))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(136, 136, 136)
                        .addComponent(addMeGroup))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mensaje)
                    .addComponent(comentario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sendMessage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMeGroup)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(comentario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(volverButton)
                    .addComponent(allUsersList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addUser)
                        .addComponent(jButton5)
                        .addComponent(sendMessage)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verGrupoDifusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verGrupoDifusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verGrupoDifusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verGrupoDifusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verGrupoDifusion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMeGroup;
    private javax.swing.JButton addUser;
    private javax.swing.JComboBox allUsersList;
    private javax.swing.JTextField comentario;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mensaje;
    private javax.swing.JButton sendMessage;
    private javax.swing.JList usersList;
    private javax.swing.JButton volverButton;
    // End of variables declaration//GEN-END:variables
}
